name: Build and Push Docker image to AWS ECR

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker Buildx for multi-platform support (optional but useful)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Set up AWS CLI (to allow authentication)
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          

      # Log in to Amazon ECR
      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t my-app .

      # Tag the Docker image with ECR repository URL
      - name: Tag Docker image
        run: |
          IMAGE_TAG=latest
          REPOSITORY_URI=692859927823.dkr.ecr.us-east-1.amazonaws.com/terraform_repo
          docker tag my-app:latest $REPOSITORY_URI:$IMAGE_TAG

      # Push the Docker image to AWS ECR
      - name: Push Docker image to ECR
        run: |
          IMAGE_TAG=latest
          REPOSITORY_URI="${{ secrets.AWS_ECR_REPOSITORY_URI }}"
          docker push $REPOSITORY_URI:$IMAGE_TAG
