name: Terraform EC2 Instance Creation

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.0 # Specify the version of Terraform you need

      # Set up AWS credentials using GitHub secrets
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init terraform/

      # Plan the Terraform execution (optional but recommended)
      - name: Terraform Plan
        run: terraform plan terraform/

      # Apply the Terraform configuration (actually provisions the EC2 instance)
      - name: Terraform Apply
        run: terraform apply -auto-approve terraform/
